### ISSUE TITLE
QA: Recent Changes fails

### ISSUE THREAD

**Issue by AlexanderPico** [BiGCAT-UM/website-monitoring#15]
The critical information to test on this page is the loading of pathway content, reflected by the descriptive count, "# pathways remaining".  Perhaps this test is failing because that content can take a while to load?  (Similar to #14).  Or does the text check not go "deep" into the page content?

https://jenkins.bigcat.unimaas.nl/job/Website%20Monitoring/lastCompletedBuild/testReport/io.github.wikipathways.academy/QA_RecentChanges/WebsiteContent/

**Comment by egonw** [comment]
I think the problem is that that line is autogenerated in the browser, not on the server side. And since we just get what the server replies but not execute the JavaScript in a page, we don't get to see the "pathways remaining" text. This is a "feature" at this moment.

I will:

1. update the test to look for something that is in the HTML returned by the server (which you can find in the Jenkins "Workspace"
2. file a feature request to "run" that HTML and it's JavaScript from the command line, and save that too

**Comment by egonw** [comment]
Feature request files at https://github.com/BiGCAT-UM/website-monitoring/issues/16
